FROM docker.io/jitesoft/lighttpd

RUN \
wget https://github.com/smart-data-lake/sdl-visualization/releases/download/0.9.2/sdl-visualizer-0.9.2.zip && \
unzip sdl-visualizer-0.9.2.zip && \
cp lighttpd.conf /etc/lighttpd/lighttpd.conf

