version = "3.10.7"

maxColumn = 160
runner.dialect = scala213

preset = default
indent.significant = 2

align.preset = some
align.arrowEnumeratorGenerator = false
align.openParenTupleSite = true
align.tokens.add = [{code = ",", owner = "Term.Tuple"}, {code = "->", owner = "Term.ApplyInfix"}]

binPack.callSite = true
binPack.indentCallSiteOnce = true
binPack.indentCallSiteSingleArg = true

newlines.selectChains.classicKeepFirst = false
newlines.source = keep

docstrings.style = Asterisk
docstrings.wrap = yes
docstrings.wrapMaxColumn = 100

rewrite.rules = [RedundantBraces, RedundantParens, SortImports]