<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>sdl-parent</artifactId>
        <groupId>io.smartdatalake</groupId>
        <version>2.8.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>


    <groupId>io.smartdatalake</groupId>
    <artifactId>sdl-debezium-connector-mariadb-shaded</artifactId>
    <version>3.1.0.Final</version>
    <packaging>jar</packaging>


    <name>sdl-debezium-connector-mariadb-shaded</name>

    <properties>
        <debezium.version>3.1.0.Final</debezium.version>
    </properties>


    <dependencies>


        <!-- Debezium dependencies start -->
        <dependency>
            <groupId>io.debezium</groupId>
            <artifactId>debezium-connector-mariadb</artifactId>
            <version>${debezium.version}</version>
        </dependency>

        <dependency>
            <groupId>io.debezium</groupId>
            <artifactId>debezium-storage-azure-blob</artifactId>
            <version>${debezium.version}</version>
        </dependency>

        <dependency>
            <groupId>io.debezium</groupId>
            <artifactId>debezium-storage-jdbc</artifactId>
            <version>${debezium.version}</version>
        </dependency>

        <dependency>
            <groupId>io.debezium</groupId>
            <artifactId>debezium-storage-redis</artifactId>
            <version>${debezium.version}</version>
        </dependency>

        <dependency>
            <groupId>io.debezium</groupId>
            <artifactId>debezium-storage-rocketmq</artifactId>
            <version>${debezium.version}</version>
        </dependency>

        <dependency>
            <groupId>io.debezium</groupId>
            <artifactId>debezium-storage-s3</artifactId>
            <version>${debezium.version}</version>
        </dependency>
        <!-- Debezium dependencies end -->




    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>shade-jar-with-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>io.debezium:**</include>
                                    <include>org.mariadb.jdbc:mariadb-java-client</include>
                                    <include>org.antlr:antlr4-runtime</include>
                                </includes>
                            </artifactSet>
                            <relocations>
                                <relocation>
                                    <pattern>org.antlr</pattern>
                                    <shadedPattern>shaded.org.antlr</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>io.debezium</pattern>
                                    <shadedPattern>shaded.io.debezium</shadedPattern>
                                </relocation>
                            </relocations>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                            </transformers>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>

                </executions>

            </plugin>
        </plugins>
    </build>


</project>
