name: Deploy to GitHub Pages

on:
  push:
    branches: [documentation]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build website
        run: |
          yarn install --frozen-lockfile
          yarn build

      #download sdl visualizer release
      #Docs: https://github.com/suisei-cn/actions-download-file
      - uses: suisei-cn/actions-download-file@v1.3.0  
        id: downloadfile  # Remember to give an ID if you need the output filename
        name: Download sdl-visualizer artifact
        with:
          url: "https://github.com/smart-data-lake/sdl-visualization/releases/latest/download/sdl-visualizer.zip"
          target: ../static/sdl-viz/
          
      #- name: Download sdl-visualizer artifact
      #  run: curl https://github.com/smart-data-lake/sdl-visualization/releases/latest/download/sdl-visualizer.zip -o ../static/sdl-viz/

      - name: Unzip sdl-visualizer artifact
        run: 7z x ../static/sdl-viz/sdl-visualizer.zip     
      
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ../static/sdl-viz/
          
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
