name: Test deployment

on:
  pull_request:
    branches: [documentation]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Test build
        run: |
          yarn install --frozen-lockfile
          yarn build
